### ISSUE TITLE
How to change the proxy port

### ISSUE THREAD

**Issue by luisee** [zhaow-de/rotating-tor-http-proxy#4]
Hi, I don't know if I'm doing it wrong, but run:

`docker run --rm -it -p 3333:3333 zhaowde/rotating-tor-http-proxy`

It doesn't make the proxy work on port 3333.

**Comment by zhaow-de** [comment]
Please refer to https://docs.docker.com/network/

It should be:
```shell
docker run --rm -it -p 3333:3128 zhaowde/rotating-tor-http-proxy
```
